# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackerRankProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackerRankProject

#  pod "ESPullToRefresh"
#  pod 'PullToRefreshSwift', '~> 3.0'
  pod "PullToRefreshKit"

  target 'HackerRankProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HackerRankProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
